import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { registerSW } from 'virtual:pwa-register'
import './index.css'
import App from './App.jsx'

// PWA: register the service worker generated by vite-plugin-pwa.
// The old kill-switch SW (public/sw.js) self-unregisters on activate, so any
// user who had it from a previous deploy will be cleanly migrated to this one.
//
// onNeedRefresh fires when a new SW has installed and is waiting. Because
// we ship workbox with skipWaiting + clientsClaim, calling updateSW(true)
// immediately swaps the active worker and reloads the page. This prevents
// the "stale chunks render a black screen mid-game" class of bug — when
// we ship a new game phase or UI change, open tabs pick it up on the next
// navigation tick instead of needing a manual hard-refresh.
//
// We DON'T auto-reload mid-gameplay though: a forced reload during a
// live Quiz Bowl game would drop the socket and trigger the engine's
// 30s abandon timer. Instead we wait until the next navigation that
// the user does themselves (or until they leave the active game).
function isInLiveGame() {
  return typeof window !== 'undefined' && /^\/game\/play\//.test(window.location.pathname);
}
const updateSW = registerSW({
  immediate: true,
  onNeedRefresh() {
    if (typeof console !== 'undefined') console.log('[Lexara] New version available');
    if (isInLiveGame()) {
      // Defer until the user navigates away from the live game. The
      // SW is already installed; it'll activate on the next page
      // load whether or not we explicitly trigger it here.
      const onPath = () => {
        if (!isInLiveGame()) {
          window.removeEventListener('popstate', onPath);
          window.removeEventListener('lexara-navigate', onPath);
          updateSW(true);
        }
      };
      window.addEventListener('popstate', onPath);
      window.addEventListener('lexara-navigate', onPath);
      return;
    }
    updateSW(true);
  },
  onOfflineReady() {
    if (typeof console !== 'undefined') console.log('[Lexara] Ready to work offline');
  },
  onRegisterError(err) {
    if (typeof console !== 'undefined') console.warn('[Lexara] SW register failed', err);
  },
});

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
