# Generated by Django 5.1.1 on 2026-05-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('difficulty', models.CharField(choices=[('fundamentals', 'Fundamentals'), ('applied', 'Applied'), ('advanced', 'Advanced')], max_length=20)),
                ('topics', models.JSONField(default=list)),
                ('questions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
